### ISSUE TITLE
why is the value of 5m-Re-rolling-up greate than 0?

### ISSUE THREAD

**Issue by 42701618** [rackerlabs/blueflood#752]
Hi team:
1.if the value that hitcount(*.com.rackspacecloud.blueflood.service.RollupService.5m-Re-rolling-up-because-of-delayed-metrics.m1_rate,"1min")  is greate than 0,what does the mean?
2.How do I following the question in the code?

thanks

**Comment by 42701618** [comment]
In ShardStateManager.java,  granToDelayedMetricsMeter  tracks the Delayed Metrics?

**Comment by ChandraAddala** [comment]
If `hitcount(*.com.rackspacecloud.blueflood.service.RollupService.5m-Re-rolling-up-because-of-delayed-metrics.m1_rate,"1min")`, it means that a slot is being re-rolled because of delayed metrics.

`granToDelayedMetricsMeter` is probably a poorly named variable. It only tracks delayed metrics which are close to TTL'ing. Any metric which is delayed by more than a day is considered close to TTLing.

All the meters in granToDelayedMetricsMeter, track the slots that are being rolled/re-rolled. If you want to just track the delayed metrics, there are couple of [meters](https://github.com/rackerlabs/blueflood/blob/master/blueflood-core/src/main/java/com/rackspacecloud/blueflood/io/Instrumentation.java#L63) which indicate if you are receiving delayed metrics.

**Comment by 42701618** [comment]
Hi ChandraAddala :
  which  couple of meters?Could you expain that?
Thank you very much.

**Comment by ChandraAddala** [comment]
I added a link in my previous reply. But here they are. 

https://github.com/rackerlabs/blueflood/blob/master/blueflood-core/src/main/java/com/rackspacecloud/blueflood/io/Instrumentation.java#L63

**Comment by 42701618** [comment]
Hi ChandraAddala :
If  a slot is re-rolled one time or twice in a short time,that is whether normal or not?

Thank you very much.

**Comment by ChandraAddala** [comment]
When blueflood receives a a metric corresponding to a slot, the slot gets rolled up after ROLLUP_DELAY_MILLIS. 

Lets say the same slot received delayed metric with smaller delay, the slots gets re-rolled after SHORT_DELAY_METRICS_ROLLUP_DELAY_MILLIS, 

Let say the same slot gets a delayed metric with a longer delay(delay greater than SHORT_DELAY_METRICS_ROLLUP_DELAY_MILLIS), it waits for LONG_DELAY_METRICS_ROLLUP_WAIT_MILLIS from the last ingested time before it re-rolls again.

So if a slot is being re-rolled, it just means that it got delayed metrics. You can play with the configurations mentioned above to control re-rolls.

**Comment by 42701618** [comment]
ChandraAddala ,thank you very much
